# Load Kedro

In [219]:
%reload_ext kedro.ipython

[12/30/25 23:01:00] INFO     Registered line magic '%reload_kedro'                                   ]8;id=244229;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=616038;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#63\63]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=529103;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=86675;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#65\65]8;;\

                    INFO     Resolved project path as:                                              ]8;id=821732;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=801268;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#180\180]8;;\
                             /Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling.
                             To set a different path, run '%reload_kedro <project_root>'

python3(67813) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python3(67814) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

[12/30/25 23:01:01] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=765988;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=95609;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

                    INFO     Kedro project fpl_modelling                                            ]8;id=223557;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=888680;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#146\146]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=377262;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=247093;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#147\147]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=419046;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=326939;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#153\153]8;;\

# Imports

In [220]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import f_oneway

In [221]:
df = catalog.load("players_hist_merged")
df

                    INFO     Loading data from players_hist_merged (SQLQueryDataset)...        ]8;id=35096;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=243917;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

,player_id,player_name,web_name,first_name,second_name,team_id,players_team,was_home,players_team_score,opponent_team_score,round,round_minutes,round_points,transfer_cost,transfers_balance,selected,transfers_in,transfers_out,ict_index,position_id,position_name,position_name_abbr,next_week_round_points,cumsum_minutes,cumsum_points,cumsum_ict_index,cumsum_transfers_in,cumsum_transfers_out,next_week_is_home,next_week_opponent_team_name
0,1,David Raya Martín,Raya,David,Raya Martín,1,Arsenal,0,1,0,1,90,10,5,0,1531911,0,0,4.9,1,Goalkeeper,GKP,6.0,90,10,4.9,0,0,1,Leeds
1,1,David Raya Martín,Raya,David,Raya Martín,1,Arsenal,1,5,0,2,90,6,5,218659,2284634,277339,58680,1.3,1,Goalkeeper,GKP,2.0,180,16,6.2,277339,58680,0,Liverpool
2,1,David Raya Martín,Raya,David,Raya Martín,1,Arsenal,0,0,1,3,90,2,5,-12311,2406964,146739,159050,3.0,1,Goalkeeper,GKP,6.0,270,18,9.2,424078,217730,1,Nott'm Forest
3,1,David Raya Martín,Raya,David,Raya Martín,1,Arsenal,1,3,0,4,90,6,5,171289,2765759,289041,117752,1.3,1,Goalkeeper,GKP,2.0,360,24,10.5,713119,335482,1,Man City
4,1,David Raya Martín,Raya,David,Raya Martín,1,Arsenal,1,1,1,5,90,2,5,-9786,2762632,98100,107886,2.1,1,Goalkeeper,GKP,2.0,450,26,12.6,811219,443368,0,Newcastle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13390,771,Tyler Fletcher,Fletcher,Tyler,Fletcher,14,Man Utd,1,1,0,18,0,0,4,0,0,0,0,0.0,3,Midfielder,MID,NaN,0,0,0.0,0,0,1,Wolves
13391,772,Sam Alabi,Alabi,Sam,Alabi,15,Newcastle,0,0,1,18,0,0,4,0,0,0,0,0.0,3,Midfielder,MID,NaN,0,0,0.0,0,0,0,Burnley
13392,773,Dean Benamar,Benamar,Dean,Benamar,8,Crystal Palace,1,0,1,18,0,0,4,0,0,0,0,0.0,2,Defender,DEF,NaN,0,0,0.0,0,0,1,Fulham
13393,774,Jenson Jones,Jenson Jones,Jenson,Jones,17,Sunderland,1,1,1,18,0,0,4,0,0,0,0,0.0,2,Defender,DEF,NaN,0,0,0.0,0,0,1,Man City
13394,775,Tymur Tutierov,Tutierov,Tymur,Tutierov,17,Sunderland,1,1,1,18,0,0,4,0,0,0,0,0.0,3,Midfielder,MID,NaN,0,0,0.0,0,0,1,Man City

In [218]:
df[df['web_name']=='Aït-Nouri']

,player_id,player_name,web_name,first_name,second_name,team_id,players_team,was_home,players_team_score,opponent_team_score,round,round_minutes,round_points,transfer_cost,transfers_balance,selected,transfers_in,transfers_out,ict_index,position_id,position_name,position_name_abbr,next_week_round_points,cumsum_minutes,cumsum_points,cumsum_ict_index,cumsum_transfers_in,cumsum_transfers_out,next_week_is_home,next_week_opponent_team_name
7218,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,4,0,1,90,9,6,0,1969933,0,0,4.7,2,Defender,DEF,1.0,90,9,4.7,0,0,1,Spurs
7219,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,0,2,2,22,1,6,262199,2527933,366735,104536,0.0,2,Defender,DEF,0.0,112,10,4.7,366735,104536,0,Brighton
7220,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,1,2,3,90,0,6,-515875,1983304,72406,588281,2.9,2,Defender,DEF,0.0,202,10,7.6,439141,692817,1,Man Utd
7221,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,3,0,4,0,0,6,-480114,1570837,40156,520270,0.0,2,Defender,DEF,0.0,202,10,7.6,479297,1213087,0,Arsenal
7222,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,1,1,5,0,0,5,-463918,1126954,508,464426,0.0,2,Defender,DEF,0.0,202,10,7.6,479805,1677513,1,Burnley
7223,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,5,1,6,0,0,5,-286641,849224,373,287014,0.0,2,Defender,DEF,0.0,202,10,7.6,480178,1964527,0,Brentford
7224,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,1,0,7,0,0,5,-136544,720387,181,136725,0.0,2,Defender,DEF,0.0,202,10,7.6,480359,2101252,1,Everton
7225,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,2,0,8,0,0,5,-75420,648256,782,76202,0.0,2,Defender,DEF,0.0,202,10,7.6,481141,2177454,0,Aston Villa
7226,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,0,1,9,0,0,5,-26914,623424,2184,29098,0.0,2,Defender,DEF,1.0,202,10,7.6,483325,2206552,1,Bournemouth
7227,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,3,1,10,1,1,5,-16309,608552,5601,21910,0.2,2,Defender,DEF,0.0,203,11,7.8,488926,2228462,1,Liverpool
7228,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,3,0,11,0,0,5,-19492,589657,1986,21478,0.0,2,Defender,DEF,0.0,203,11,7.8,490912,2249940,0,Newcastle
7229,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,1,2,12,0,0,5,-13940,576880,4213,18153,0.0,2,Defender,DEF,0.0,203,11,7.8,495125,2268093,1,Leeds
7230,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,3,2,13,0,0,5,-9379,568214,4768,14147,0.0,2,Defender,DEF,0.0,203,11,7.8,499893,2282240,0,Fulham
7231,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,5,4,14,0,0,5,-10585,558176,1321,11906,0.0,2,Defender,DEF,0.0,203,11,7.8,501214,2294146,1,Sunderland
7232,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,3,0,15,0,0,5,-13780,544810,1505,15285,0.0,2,Defender,DEF,1.0,203,11,7.8,502719,2309431,0,Crystal Palace
7233,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,3,0,16,1,1,5,-16398,529036,4295,20693,1.3,2,Defender,DEF,0.0,204,12,9.1,507014,2330124,1,West Ham
7234,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,1,3,0,17,0,0,5,-21790,507156,82,21872,0.0,2,Defender,DEF,0.0,204,12,9.1,507096,2351996,0,Nott'm Forest
7235,402,Rayan Aït-Nouri,Aït-Nouri,Rayan,Aït-Nouri,13,Man City,0,2,1,18,0,0,5,-12204,495378,46,12250,0.0,2,Defender,DEF,NaN,204,12,9.1,507142,2364246,0,Sunderland

In [212]:
jd = catalog.load("joined_data").sort_values(by=['round', 'rank'])

[12/22/25 20:01:41] INFO     Loading data from joined_data (ParquetDataset)...                 ]8;id=436265;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=16615;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

In [213]:
jd

,player_id,player_name,web_name,first_name,second_name,team_id,players_team,was_home,players_team_score,opponent_team_score,round,round_minutes,round_points,transfer_cost,transfers_balance,selected,transfers_in,transfers_out,ict_index,position_id,position_name,position_name_abbr,next_week_round_points,cumsum_minutes,cumsum_points,cumsum_ict_index,cumsum_transfers_in,cumsum_transfers_out,next_week_is_home,next_week_opponent_team_name,predicted_next_week_points,rank
0,205,Josh Cullen,Cullen,Josh,Cullen,3,Burnley,1,2,0,2,90,14,5,2529,10357,3654,1125,10.4,3,Midfielder,MID,2.0,180,18,18.7,3654,1125,0,Man Utd,8.652070,1
1,200,Jaidon Anthony,Anthony,Jaidon,Anthony,3,Burnley,1,2,0,2,90,13,5,533,14201,2572,2039,10.1,3,Midfielder,MID,6.0,174,15,16.6,2572,2039,0,Man Utd,8.096241,2
2,287,Jordan Pickford,Pickford,Jordan,Pickford,9,Everton,1,2,0,2,90,15,5,-64855,1130150,21753,86608,5.0,1,Goalkeeper,GKP,1.0,180,17,7.1,21753,86608,0,Wolves,7.212047,3
3,190,Hjalmar Ekdal,Ekdal,Hjalmar,Ekdal,3,Burnley,1,2,0,2,90,9,4,2434,28743,5086,2652,5.0,2,Defender,DEF,3.0,180,10,6.8,5086,2652,0,Man Utd,6.498701,4
4,84,Marcus Tavernier,Tavernier,Marcus,Tavernier,4,Bournemouth,1,1,0,2,77,11,5,16235,64769,24795,8560,7.5,3,Midfielder,MID,3.0,167,15,14.7,24795,8560,0,Spurs,6.450024,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,575,Micky van de Ven,Van de Ven,Micky,van de Ven,18,Spurs,1,2,0,15,90,6,4,-205732,3795149,31026,236758,2.0,2,Defender,DEF,1.0,1249,64,45.7,2578867,2050616,0,Nott'm Forest,5.022650,11
206,470,Martin Dúbravka,Dúbravka,Martin,Dúbravka,3,Burnley,0,1,2,15,90,3,4,-13058,4226333,27370,40428,3.3,1,Goalkeeper,GKP,1.0,1350,43,43.2,1150048,776102,1,Fulham,3.140722,12
207,710,Travis Patterson,Patterson,Travis,Patterson,2,Aston Villa,1,2,1,15,0,0,3,-463,29431,478,941,0.0,2,Defender,DEF,0.0,0,0,0.0,30999,14330,0,West Ham,0.072266,13
208,45,Lino da Cruz Sousa,Sousa,Lino,da Cruz Sousa,2,Aston Villa,1,2,1,15,0,0,3,-297,37552,433,730,0.0,2,Defender,DEF,0.0,0,0,0.0,15642,26366,0,West Ham,0.068790,14
209,364,Mateo Joseph Fernández-Regatillo,Mateo Joseph,Mateo,Joseph Fernández-Regatillo,11,Leeds,1,3,3,15,0,0,5,-4,1292,0,4,0.0,4,Forward,FWD,0.0,0,0,0.0,0,2371,0,Brentford,0.044271,15

In [204]:
jd_15 = jd[jd['round']==15]
jd_15[['player_name', 'round', 'round_minutes', 'round_points', 'next_week_round_points', 'predicted_next_week_points','rank']]

,player_name,round,round_minutes,round_points,next_week_round_points,predicted_next_week_points,rank
195,Bruno Borges Fernandes,15,90,18,13.0,7.209744,1
196,Declan Rice,15,90,6,2.0,6.702408,2
197,David Raya Martín,15,90,2,2.0,6.199129,3
198,Jurriën Timber,15,90,3,2.0,6.102606,4
199,Pedro Porro Sauceda,15,90,5,0.0,5.798901,5
200,Bryan Mbeumo,15,90,8,2.0,5.767007,6
201,Bruno Guimarães Rodriguez Moura,15,90,10,1.0,5.425586,7
202,Kiernan Dewsbury-Hall,15,90,16,1.0,5.329699,8
203,Igor Thiago Nascimento Rodrigues,15,90,2,2.0,5.253995,9
204,Richarlison de Andrade,15,90,8,2.0,5.146576,10
205,Micky van de Ven,15,90,6,1.0,5.022650,11
206,Martin Dúbravka,15,90,3,1.0,3.140722,12
207,Travis Patterson,15,0,0,0.0,0.072266,13
208,Lino da Cruz Sousa,15,0,0,0.0,0.068790,14
209,Mateo Joseph Fernández-Regatillo,15,0,0,0.0,0.044271,15

In [205]:
jd_15_starts = jd_15[jd_15['rank']<=11]
true_points = jd_15_starts['round_points'].sum() + jd_15_starts[jd_15_starts['rank']==1]['round_points'].values
true_points[0]

np.int64(102)

In [206]:
df[df['round']==16]['next_week_round_points']

15      NaN
31      NaN
47      NaN
63      NaN
79      NaN
         ..
11840   NaN
11843   NaN
11846   NaN
11848   NaN
11849   NaN
Name: next_week_round_points, Length: 760, dtype: float64

In [78]:
model_config = catalog.load("params:model_config")[4]

                    INFO     Loading data from params:model_config (MemoryDataset)...          ]8;id=469655;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=836924;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

In [208]:
catalog.load("params:average_points").values()

[12/19/25 21:49:40] INFO     Loading data from params:average_points (MemoryDataset)...        ]8;id=871656;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=470945;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

dict_values([54, 51, 48, 63, 42, 46, 60, 56, 46, 65, 38, 39, 35, 58, 49, 60])

In [87]:
import typing as tp 
def load_config(model_config: tp.Dict, model_num: int):
    """
    Load model pipeline
    """

    model_config = model_config[model_num]
    builder = ModelPipelineBuilder(model_config) 
    pipeline = builder.build_pipeline()

    features = model_config['features']['num_features'] + model_config['features']['cat_features']

    return pipeline, features

def train_test_split(df:pd.DataFrame, predicting_gameweek: int):
    """
    Split data into train and test, test dat being num_test_gameweeks most recent gameweeks
    """

    test_df = df[df['round']==predicting_gameweek].reset_index(drop=True)
    train_df = df[df['round'] < predicting_gameweek].reset_index(drop=True)

    return train_df, test_df


def train_model(train_df: pd.DataFrame, pipeline: sklearn.pipeline.Pipeline, features: tp.List[str], 
                mlflow_tracking_uri: str, predicting_gameweek: int, target_col: str='next_week_round_points'):

    mlflow.set_tracking_uri(mlflow_tracking_uri)
    mlflow.set_experiment(f"gameweek_{predicting_gameweek}")
    X = train_df[features]
    y = train_df[target_col]

    with mlflow.start_run(run_name="fpl_model_training") as run:
        pipeline.fit(X, y)

        model_info = mlflow.sklearn.log_model(
            sk_model=pipeline,
            artifact_path="model",
            registered_model_name=f"model_gameweek_{predicting_gameweek}",
        )

    return pipeline

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:26                                                                                   │
│                                                                                                  │
│   23 │   return train_df, test_df                                                                │
│   24                                                                                             │
│   25                                                                                             │
│ ❱ 26 def train_model(train_df: pd.DataFrame, pipeline: sklearn.pipeline.Pipeline, features: t    │
│   27 │   │   │   │   mlflow_tracking_uri: str, predicting_gameweek: int, target_col: str='nex    │
│   28 │                                                                                           │
│   29 │   mlflow.set_tracking_uri(mlflow_tracking_uri)                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'sklearn' is not defined

In [82]:
# features:
#  num_features: 
#   prev_gameweeks:
#     accumulated_minutes:
#         num_prev_games: 3
#         average_type: ma
#     ict_index:
#         num_prev_games: 3
#         average_type: ema
#  cat_features: 
#   next_gameweek:
#     - next_week_is_home
#     - next_week_opponent_team