# Load Kedro

In [104]:
%reload_ext kedro.ipython

[12/13/25 17:03:46] INFO     Registered line magic '%reload_kedro'                                   ]8;id=228875;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=338757;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#63\63]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=750095;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=920783;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#65\65]8;;\

                    INFO     Resolved project path as:                                              ]8;id=863380;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=534671;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#180\180]8;;\
                             /Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling.
                             To set a different path, run '%reload_kedro <project_root>'

python3(3272) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python3(3273) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=696499;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=866713;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

[12/13/25 17:03:47] INFO     Kedro project fpl_modelling                                            ]8;id=283446;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=36372;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#146\146]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=905494;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=553298;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#147\147]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=632222;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=904913;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#153\153]8;;\

# Imports

In [105]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import f_oneway

In [76]:
df = catalog.load("players_hist_merged")
df

                    INFO     Loading data from players_hist_merged (SQLQueryDataset)...        ]8;id=593968;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=380487;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

,player_id,web_name,first_name,second_name,team_id,players_team,was_home,players_team_score,opponent_team_score,round,...,position_id,position_name,position_name_abbr,cumsum_minutes,cumsum_points,cumsum_ict_index,cumsum_transfers_in,cumsum_transfers_out,next_week_is_home,next_week_opponent_team_name
0,1,Raya,David,Raya Martín,1,Arsenal,0,1,0,1,...,1,Goalkeeper,GKP,90,10,4.9,0,0,1,Leeds
1,1,Raya,David,Raya Martín,1,Arsenal,1,5,0,2,...,1,Goalkeeper,GKP,180,16,6.2,277339,58680,0,Liverpool
2,1,Raya,David,Raya Martín,1,Arsenal,0,0,1,3,...,1,Goalkeeper,GKP,270,18,9.2,424078,217730,1,Nott'm Forest
3,1,Raya,David,Raya Martín,1,Arsenal,1,3,0,4,...,1,Goalkeeper,GKP,360,24,10.5,713119,335482,1,Man City
4,1,Raya,David,Raya Martín,1,Arsenal,1,1,1,5,...,1,Goalkeeper,GKP,450,26,12.6,811219,443368,0,Newcastle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9568,753,Ruddy,John,Ruddy,15,Newcastle,0,4,1,13,...,1,Goalkeeper,GKP,0,0,0.0,110,10,1,Spurs
9569,754,George Hemmings,George,Hemmings,2,Aston Villa,0,2,1,12,...,3,Midfielder,MID,0,0,0.0,0,0,1,Wolves
9570,754,George Hemmings,George,Hemmings,2,Aston Villa,1,1,0,13,...,3,Midfielder,MID,0,0,0.0,47,7,0,Brighton
9571,755,Lacey,Shea,Lacey,14,Man Utd,1,0,1,12,...,3,Midfielder,MID,0,0,0.0,0,0,0,Crystal Palace
9572,755,Lacey,Shea,Lacey,14,Man Utd,0,2,1,13,...,3,Midfielder,MID,0,0,0.0,45,3,1,West Ham

In [77]:
df[df['round']==13]

,player_id,web_name,first_name,second_name,team_id,players_team,was_home,players_team_score,opponent_team_score,round,...,position_id,position_name,position_name_abbr,cumsum_minutes,cumsum_points,cumsum_ict_index,cumsum_transfers_in,cumsum_transfers_out,next_week_is_home,next_week_opponent_team_name
12,1,Raya,David,Raya Martín,1,Arsenal,0,1,1,13,...,1,Goalkeeper,GKP,1170,58,19.7,2395871,1012244,1,Brentford
25,2,Arrizabalaga,Kepa,Arrizabalaga Revuelta,1,Arsenal,0,1,1,13,...,1,Goalkeeper,GKP,0,0,0.0,8509,62796,1,Brentford
38,3,Hein,Karl,Hein,1,Arsenal,0,1,1,13,...,1,Goalkeeper,GKP,0,0,0.0,5545,41919,1,Brentford
51,4,Setford,Tommy,Setford,1,Arsenal,0,1,1,13,...,1,Goalkeeper,GKP,0,0,0.0,16264,18020,1,Brentford
64,5,Gabriel,Gabriel,dos Santos Magalhães,1,Arsenal,0,1,1,13,...,2,Defender,DEF,990,81,46.9,3873595,3576120,1,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9563,751,Akhamrich,Yusuf,Akhamrich,18,Spurs,1,1,2,13,...,3,Midfielder,MID,0,0,0.0,174,52,0,Newcastle
9566,752,Golambeckis,Airidas,Golambeckis,19,West Ham,1,0,2,13,...,2,Defender,DEF,0,0,0.0,220,110,0,Man Utd
9568,753,Ruddy,John,Ruddy,15,Newcastle,0,4,1,13,...,1,Goalkeeper,GKP,0,0,0.0,110,10,1,Spurs
9570,754,George Hemmings,George,Hemmings,2,Aston Villa,1,1,0,13,...,3,Midfielder,MID,0,0,0.0,47,7,0,Brighton
9572,755,Lacey,Shea,Lacey,14,Man Utd,0,2,1,13,...,3,Midfielder,MID,0,0,0.0,45,3,1,West Ham

In [78]:
model_config = catalog.load("params:model_config")[4]

                    INFO     Loading data from params:model_config (MemoryDataset)...          ]8;id=469655;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=836924;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

In [80]:
df[f"next_week_round_points"] = df.groupby('player_id')['round_points'].shift(-1)

In [87]:
import typing as tp 
def load_config(model_config: tp.Dict, model_num: int):
    """
    Load model pipeline
    """

    model_config = model_config[model_num]
    builder = ModelPipelineBuilder(model_config) 
    pipeline = builder.build_pipeline()

    features = model_config['features']['num_features'] + model_config['features']['cat_features']

    return pipeline, features

def train_test_split(df:pd.DataFrame, predicting_gameweek: int):
    """
    Split data into train and test, test dat being num_test_gameweeks most recent gameweeks
    """

    test_df = df[df['round']==predicting_gameweek].reset_index(drop=True)
    train_df = df[df['round'] < predicting_gameweek].reset_index(drop=True)

    return train_df, test_df


def train_model(train_df: pd.DataFrame, pipeline: sklearn.pipeline.Pipeline, features: tp.List[str], 
                mlflow_tracking_uri: str, predicting_gameweek: int, target_col: str='next_week_round_points'):

    mlflow.set_tracking_uri(mlflow_tracking_uri)
    mlflow.set_experiment(f"gameweek_{predicting_gameweek}")
    X = train_df[features]
    y = train_df[target_col]

    with mlflow.start_run(run_name="fpl_model_training") as run:
        pipeline.fit(X, y)

        model_info = mlflow.sklearn.log_model(
            sk_model=pipeline,
            artifact_path="model",
            registered_model_name=f"model_gameweek_{predicting_gameweek}",
        )

    return pipeline

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:26                                                                                   │
│                                                                                                  │
│   23 │   return train_df, test_df                                                                │
│   24                                                                                             │
│   25                                                                                             │
│ ❱ 26 def train_model(train_df: pd.DataFrame, pipeline: sklearn.pipeline.Pipeline, features: t    │
│   27 │   │   │   │   mlflow_tracking_uri: str, predicting_gameweek: int, target_col: str='nex    │
│   28 │                                                                                           │
│   29 │   mlflow.set_tracking_uri(mlflow_tracking_uri)                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'sklearn' is not defined

In [82]:
# features:
#  num_features: 
#   prev_gameweeks:
#     accumulated_minutes:
#         num_prev_games: 3
#         average_type: ma
#     ict_index:
#         num_prev_games: 3
#         average_type: ema
#  cat_features: 
#   next_gameweek:
#     - next_week_is_home
#     - next_week_opponent_team