# Load Kedro

In [184]:
%reload_ext kedro.ipython

[05/09/26 15:43:29] INFO     Registered line magic '%reload_kedro'                                   ]8;id=661441;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=38041;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#63\63]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=300708;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=965879;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#65\65]8;;\

                    INFO     Resolved project path as:                                              ]8;id=404715;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=999512;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#180\180]8;;\
                             /Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling.
                             To set a different path, run '%reload_kedro <project_root>'

python3(7229) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.
python3(7230) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

[05/09/26 15:43:30] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=340944;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py\plugin.py]8;;\:]8;id=132934;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro_telemetry/plugin.py#243\243]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

                    INFO     Kedro project fpl_modelling                                            ]8;id=446415;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=239191;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#146\146]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=204536;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=180542;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#147\147]8;;\
                             'pipelines'

                    INFO     Registered line magic 'run_viz'                                        ]8;id=865229;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=265331;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/ipython/__init__.py#153\153]8;;\

# Imports

In [185]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import f_oneway

In [186]:
pd.set_option('display.max_columns', None)

Load players_hist_merged dataframe

In [187]:
minute_threshold = 0

In [188]:
df = catalog.load("players_hist_merged")

# df = df[df['cumsum_minutes']>minute_threshold]

                    INFO     Loading data from players_hist_merged (SQLQueryDataset)...        ]8;id=187680;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=193079;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

In [189]:
# Check if any player has duplicate rounds

duplicates = (
    df.groupby(["player_name", "round"])
      .size()
      .reset_index(name="count")
      .query("count > 1")
)

print(duplicates)

           player_name  round  count
103       Aaron Ramsey     32      2
104       Aaron Ramsey     33      2
174    Aarón Anselmino     32      2
175    Aarón Anselmino     33      2
209      Abdallah Sima     32      2
...                ...    ...    ...
27614   Đorđe Petrović     33      2
27647   İlkay Gündoğan     32      2
27648   İlkay Gündoğan     33      2
27649   İlkay Gündoğan     35      2
27650   İlkay Gündoğan     36      2

[817 rows x 3 columns]

In [190]:
df[(df['player_name']=='Aaron Ramsey') & (df['round']==32)]

,player_id,player_name,web_name,first_name,second_name,team_id,players_team,was_home,players_team_score,opponent_team_score,round,round_minutes,round_points,transfer_cost,transfers_balance,selected,transfers_in,transfers_out,ict_index,position_id,position_name,position_name_abbr,next_week_round_points,next_week_round_minutes,cumsum_minutes,cumsum_points,cumsum_ict_index,cumsum_transfers_in,cumsum_transfers_out,next_week_is_home,next_week_opponent_team_name,next_week_fixture_count,next_week_dgw
7729,211,Aaron Ramsey,A.Ramsey,Aaron,Ramsey,3,Burnley,1,0.0,2.0,32,0,0,4,-540,183756,0,540,0.0,3,Midfielder,MID,0.0,0.0,0,0,0.0,62789,932831,0.0,Nott'm Forest,2,1
7730,211,Aaron Ramsey,A.Ramsey,Aaron,Ramsey,3,Burnley,1,0.0,2.0,32,0,0,4,-540,183756,0,540,0.0,3,Midfielder,MID,0.0,0.0,0,0,0.0,62789,932831,1.0,Man City,2,1

In [191]:
df['next_week_fixture_count'].value_counts()

next_week_fixture_count
1    26673
2     1138
0      657
Name: count, dtype: int64

In [192]:
fixtures = catalog.load("fixtures")
fixtures[fixtures['event']==30]

[05/09/26 15:43:31] INFO     Loading data from fixtures (SQLTableDataset)...                   ]8;id=369534;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=550852;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,team_h_difficulty,team_a_difficulty,pulse_id,gameweek
291,2562187,30,True,True,293,2026-03-14T15:00:00Z,90,False,True,4,0.0,3,0.0,3,2,125083,30
292,2562193,30,True,True,299,2026-03-14T15:00:00Z,90,False,True,6,1.0,17,0.0,3,3,125089,30
293,2562185,30,True,True,291,2026-03-14T17:30:00Z,90,False,True,9,0.0,1,2.0,3,5,125081,30
294,2562188,30,True,True,294,2026-03-14T17:30:00Z,90,False,True,15,1.0,7,0.0,3,3,125084,30
295,2562194,30,True,True,300,2026-03-14T20:00:00Z,90,False,True,13,1.0,19,1.0,4,3,125090,30
296,2562189,30,True,True,295,2026-03-15T14:00:00Z,90,False,True,11,0.0,8,0.0,2,3,125085,30
297,2562191,30,True,True,297,2026-03-15T14:00:00Z,90,False,True,2,1.0,14,3.0,3,4,125087,30
298,2562192,30,True,True,298,2026-03-15T14:00:00Z,90,False,True,10,0.0,16,0.0,3,3,125088,30
299,2562190,30,True,True,296,2026-03-15T16:30:00Z,90,False,True,18,1.0,12,1.0,3,4,125086,30
300,2562186,30,True,True,292,2026-03-16T20:00:00Z,90,False,True,20,2.0,5,2.0,1,3,125082,30

In [193]:
from fpl_modelling.pipelines.data_science.train_model_nodes import load_config, train_test_split, train_model
from fpl_modelling.pipelines.data_science.data_processing_nodes import preprocess_data, eng_rolling_avg_features
from fpl_modelling.pipelines.data_science.eval_model_hist_nodes import _get_train_test_predictions, _get_optimal_team_test_prediction

In [194]:
model_config = {
    4: {
        "minute_threshold": 1,
        "features": {
            "num_features": [
                "cumsum_minutes",
                "transfers_in_ewm_5",
                "ict_index_ewm_5",
                "selected",
            ],
            "cat_features": [
                "next_week_is_home",
                "players_team",
                "next_week_opponent_team_name",
                "position_name",
            ],
        },
        "preprocessor": {
            "steps": [
                {
                    "name": "num",
                    "transformer": "sklearn.preprocessing.RobustScaler",
                    "columns": [
                        "cumsum_minutes",
                        "transfers_in_ewm_5",
                        "ict_index_ewm_5",
                        "selected",
                    ],
                },
                {
                    "name": "cat",
                    "transformer": "sklearn.preprocessing.OneHotEncoder",
                    "columns": [
                        "next_week_is_home",
                        "players_team",
                        "next_week_opponent_team_name",
                        "position_name",
                    ],
                },
            ]
        },
        "model": {
            "class": "xgboost.XGBRegressor",
            "hyperparams": {
                "booster": "gbtree",
                "colsample_bylevel": 0.8203728667728196,
                "colsample_bytree": 0.922991157077929,
                "gamma": 4.158210875794536,
                "learning_rate": 0.006952873032336879,
                "max_depth": 5,
                "min_child_weight": 1,
                "n_estimators": 773,
                "reg_alpha": 0.008785958264239105,
                "reg_lambda": 5.742011472489027e-07,
                "subsample": 0.8604270021819085,
                "random_state": 42,
            },
        },
    }
}

In [195]:
rolling_features = {
            'transfers_in': {'method': 'ewm', 'n': 5},
            'ict_index': {'method': 'ewm', 'n': 5},
        }

In [196]:
df = eng_rolling_avg_features(df, rolling_features)

In [197]:
pipeline, features = load_config(model_config, model_num=4)
train_df, test_df = train_test_split(df=df, predicting_gameweek=35)

In [198]:
model = train_model(train_df, pipeline,features,predicting_gameweek =35, mlflow_tracking_uri=None)

['cumsum_minutes', 'transfers_in_ewm_5', 'ict_index_ewm_5', 'selected', 'next_week_is_home', 'players_team', 'next_week_opponent_team_name', 'position_name']

In [199]:
y_pred_test, y_true_test, y_pred_train, y_true_train = _get_train_test_predictions(test_df, train_df, features, model, target_col='next_week_round_points')

[05/09/26 15:43:32] INFO     Generated predictions - Test samples: 914, Train samples:  ]8;id=268704;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/src/fpl_modelling/pipelines/data_science/eval_model_hist_nodes.py\eval_model_hist_nodes.py]8;;\:]8;id=157845;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/src/fpl_modelling/pipelines/data_science/eval_model_hist_nodes.py#83\83]8;;\
                             26640

In [200]:
opt_team = _get_optimal_team_test_prediction(test_df,y_pred_test,y_true_test,objective_col_name="predicted_next_week_points")

python3(7238) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

[05/09/26 15:43:34] INFO     Optimal team selected successfully                        ]8;id=540969;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/src/fpl_modelling/pipelines/data_science/eval_model_hist_nodes.py\eval_model_hist_nodes.py]8;;\:]8;id=115610;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/src/fpl_modelling/pipelines/data_science/eval_model_hist_nodes.py#157\157]8;;\

In [208]:
opt_team['squad_ranking']

,player_name,predicted_next_week_points,position_name,team_id,rank
429,Erling Haaland,11.286215,Forward,13,1
259,Marc Guéhi,11.181897,Defender,13,2
81,Antoine Semenyo,9.986806,Midfielder,13,3
257,Tyrick Mitchell,7.237412,Defender,8,4
256,Maxence Lacroix,6.989136,Defender,8,5
448,Bruno Borges Fernandes,6.431320,Midfielder,14,6
252,Dean Henderson,6.031355,Goalkeeper,8,7
456,Carlos Henrique Casimiro,5.837159,Midfielder,14,8
147,Ferdi Kadıoğlu,5.779169,Defender,6,9
63,Ollie Watkins,5.674665,Forward,2,10
449,Matheus Santos Carneiro da Cunha,5.660755,Midfielder,14,11
816,Adam Armstrong,2.067220,Forward,20,12
489,Joelinton Cássio Apolinário de Lira,1.796528,Midfielder,15,13
184,Václav Hladký,0.033754,Goalkeeper,3,14
759,Wellity Lucky,0.030448,Defender,12,15

In [201]:
picked_team_gw = opt_team['squad'] 

true_players_stats = df[
            (df['round'] == 35) & 
            (df['player_name'].isin(picked_team_gw))
        ]
predictions = opt_team['squad_ranking'][['player_name', 'predicted_next_week_points', 'rank']]
        
# Merge actual stats with predictions
joined_data = true_players_stats.merge(
    predictions, 
    on='player_name', 
    how='inner'
).sort_values(by='rank')

In [202]:
# Aggregate to player level (handles DGWs correctly)
agg_df = (
    joined_data
    .groupby(['player_id'], as_index=False)
    .agg({
        "predicted_next_week_points": 'sum',              # predicted points
        'next_week_round_points': 'sum',         # actual points
        'transfer_cost': 'first',
        'position_name': 'first',
        'players_team': 'first',
        'player_name': 'first'
    })
)

In [203]:
avg_points = catalog.load("params:average_points")

                    INFO     Loading data from params:average_points (MemoryDataset)...        ]8;id=36052;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=447453;file:///Users/eoinmolloy/Documents/Documents/FPL-Modelling/fpl-modelling/.venv/lib/python3.12/site-packages/kedro/io/data_catalog.py#1046\1046]8;;\

In [204]:
gw_starters = joined_data[joined_data['rank']<=11]

true_points = gw_starters['next_week_round_points'].sum() + gw_starters[gw_starters['rank']==1]['next_week_round_points'].values
true_points

array([28., 21.])

In [205]:
avg_points[35]

30